Implement AMMs router
parallel-finance/parallel pull request #465
Opened 2021-08-25 16:52 UTC by rustaceanstayhigh

Closed #457

2021-08-30 10:30 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +        type AMMs: Get<Route<Self>>;
This should be a vec of instances implementing the AMM trait

2021-08-30 10:30 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +        type AMM: AMM<Self::AccountId, CurrencyId, BalanceOf<Self>>;
This should be parts of `AMMs`

2021-08-30 10:30 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +                amount_in > Zero::zero() && min_amount_out > Zero::zero(),
I guess min amount could be 0

2021-08-30 10:51 UTC, ashi20192020ayush submitted a review, later dismissed

2021-08-30 10:51 UTC, ashi20192020ayush commented on pallets/router/src/lib.rs
> +        EnptyRouters,
```suggestion
        EmptyRouters,
```

Spelling Mistake

2021-08-30 10:51 UTC, ashi20192020ayush commented on pallets/router/src/lib.rs
> +        BalanceLow,
Please add comment before each errors like other pallets

2021-08-30 10:51 UTC, ashi20192020ayush commented on pallets/router/src/lib.rs
> +        #[pallet::weight(10_000)]
Can we add comment here?

2021-09-16 10:33 UTC, ETeissonniere requested changes

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +//! Given a supported `route` like this `(0, USDT, KSM)`, we can get corresponding AMM or pool.
```suggestion
//! # Router for Automatic Market Maker (AMM)
//!
//! Given a supported `route`, executes the indicated trades on all the available AMM(s) pool(s).
```

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +                let (_id, from_currency_id, to_currency_id) = sub_route;
```suggestion
                let (from_currency_id, to_currency_id) = sub_route;
```

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +    )>;
```suggestion
    pub type Route = Vec<(
        // Base asset
        CurrencyId,
        // Quote asset
        CurrencyId,
    )>;
```

for now we only have one AMM due to our simplification efforts

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +        type RoutePalletId: Get<PalletId>;
```suggestion
        /// Router pallet id
        #[pallet::constant]
        type RouterPalletId: Get<PalletId>;
```

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +        type AMMAdaptor: AMM<Self>;
```suggestion
        type AMM: AMM<Self>;
```

only one AMM and no adapter in this simplified design

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +        type Routes: Get<Route>;
```suggestion
```

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +        type MaxLengthRoute: Get<u8>;
we could modify `Route` from `Vec` to a `BoundedVec` to avoid this

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +                )?;
```suggestion
                amount_out = T::AMMAdaptor::trade(
                    &trader,
                    (*from_currency_id, *to_currency_id),
                    amount_in,
                    min_amount_out,
                )?;
```

this got me confused 😉

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +
```suggestion
```

I believe this is unnecessary

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +    }
```suggestion
    #[pallet::error]
    pub enum Error<T> {
        /// Input balance must not be zero
        ZeroBalance,
        /// Must input one route at least
        EmptyRoute,
        /// User hasn't enough tokens for transaction
        InsufficientBalance,
        /// The expiry is smaller than current block number
        TooSmallExpiry,
        /// Exceed the max length of routes we allow
        ExceedMaxLengthRoute,
        /// Input duplicated route
        DuplicatedRoute,
    }
```

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/mock.rs
> +}
we don't rely on the `on_initialize` and `on_finalize` functions for this pallet. Thus we should be able to replace this as below:
```suggestion
pub(crate) fn run_to_block(n: u64) {
    System::set_block_number(n);
}
```

2021-09-16 10:33 UTC, ETeissonniere commented on pallets/router/src/tests.rs
> +}
This test is great however it doesn't cover the case of a cross pool trade (where we have more than one route). Let's add one to cover this.

2021-09-20 12:18 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +
```suggestion
            for sub_route in route.iter() {
                let (from_currency_id, to_currency_id) = sub_route;

                amount_out = T::AMM::trade(
                    &trader,
                    (*from_currency_id, *to_currency_id),
                    amount_in,
                    1,
                )?;

                amount_in = amount_out;
            }
            
            ensure!(amount_out >= min_amount_out, Error::<T>::UnexpectedSlippage);

```

2021-09-20 12:18 UTC, ETeissonniere commented on pallets/router/src/lib.rs
> +        DuplicatedRoute,
```suggestion
        /// Input duplicated route
        DuplicatedRoute,
        /// We received less coins than the minimum amount specified
        UnexpectedSlippage,
```

2021-09-20 12:50 UTC, ETeissonniere approved these changes

2021-09-20 13:34 UTC, drbh commented
@rustaceanstayhigh LGTM 👌 except for the CI build error 

```
the package `parallel-runtime` depends on `pallet-router`, with features: `pallet-balances` but `pallet-router` does not have these features.
```

2021-09-22 07:39 UTC, merged