Emergency shutdown
parallel-finance/parallel pull request #913
Opened 2021-11-23 11:18 UTC by ashi20192020ayush

2021-11-23 12:10 UTC, ETeissonniere requested changes

2021-11-23 12:10 UTC, ETeissonniere commented on runtime/heiko/src/lib.rs
> +}
We need to define a new filter here. Not patch the existing one.

2021-11-23 12:10 UTC, ETeissonniere commented on runtime/heiko/src/lib.rs
> +    type Whitelist = WhiteListFilter;
This should be the new filter we define previously

2021-11-26 02:51 UTC, GopherJ commented
I'm still a bit confused on this. What if we only want to shutdown crowdloan pallet's certain calls + loans pallet's certain calls?

2021-11-26 07:48 UTC, ETeissonniere commented
@GopherJ that would not be possible. The goal of the emergency shutdown pallet is to shut down all non-critical operations in the event of a major issue. If we wanted to resume operations for one pallet or the other this would have to go through either:
1. Disabling the emergency shut down state all together
2. Issuing a runtime upgrade to reactivate some of the pallets we think are safe to reopen

2021-11-29 00:39 UTC, GopherJ commented
> @GopherJ that would not be possible. The goal of the emergency shutdown pallet is to shut down all non-critical operations in the event of a major issue. If we wanted to resume operations for one pallet or the other this would have to go through either:
> 
>     1. Disabling the emergency shut down state all together
> 
>     2. Issuing a runtime upgrade to reactivate some of the pallets we think are safe to reopen

ok got it

2021-11-29 00:40 UTC, GopherJ commented on runtime/heiko/src/lib.rs
> +        EmergencyShutdown: pallet_emergency_shutdown::{Pallet, Call, Event<T>} = 84,
84 shouldn't be put after 90

2021-11-29 00:41 UTC, GopherJ commented on runtime/parallel/src/lib.rs
> +			Call::EmergencyShutdown(_)
this should be aligned

2021-11-29 00:41 UTC, GopherJ commented on runtime/vanilla/src/lib.rs
> +			Call::EmergencyShutdown(_)
should be aligned

2021-11-29 00:41 UTC, GopherJ commented on runtime/heiko/src/lib.rs
> +			Call::EmergencyShutdown(_)
should be aligned

2021-11-29 06:01 UTC, GopherJ commented on runtime/parallel/src/lib.rs
> +        EmergencyShutdown: pallet_emergency_shutdown::{Pallet, Call, Event<T>} = 84,
this index isn't correct

2021-11-29 06:01 UTC, GopherJ commented on runtime/vanilla/src/lib.rs
> +        EmergencyShutdown: pallet_emergency_shutdown::{Pallet, Call, Event<T>} = 84,
this index looks incorrect

2021-11-29 06:03 UTC, GopherJ commented on runtime/heiko/src/lib.rs
> +pub enum CallFilterRouter {}
empty struct is better

2021-11-29 08:51 UTC, GopherJ commented on pallets/emergency-shutdown/src/lib.rs
> +        if Self::is_shut_down_flag() {
can be simplified by:

```rust
!Self::is_shut_down_flag() ||  T::Whitelist::contains(call)
```

2021-11-29 11:24 UTC, ETeissonniere approved these changes

2021-11-29 14:15 UTC, merged